[tool.poetry]
name = "mini-toolbox"
version = "0.0.0"
description = ""
authors = ["likianta <likianta@foxmail.com>"]
packages = [{include = "mini_toolbox"}]

[tool.poetry.dependencies]
python = "^3.12"
# argsense = "*"
argsense = { version = "^0.6.0", source = "likianta-host" }
google-cloud-translate = "^3.19.0"
# hyperdiv = "^0.1.3"
ipython = "*"
lk-logger = { version = "^6.0.3", source = "likianta-host" }
lk-utils = { version = "^3.1.2a5", source = "likianta-host" }
markdown2 = "^2.5.2"
markdownify = "^0.14.1"
pillow = "^10.4.0"
pyperclip = "^1.9.0"
streamlit = "^1.40.0"
streamlit-canary = { version = "^0.1.0a11", source = "likianta-host" }
streamlit-code-editor = "^0.1.21"
# streamlit-shadcn-ui = "^0.1.17"

[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
priority = "primary"

[[tool.poetry.source]]
name = "likianta-host"
url = "http://likianta.pro:2131/"
priority = "supplemental"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
