[tool.poetry]
name = "mini-toolbox"
version = "0.1.0"
description = ""
authors = ["likianta <likianta@foxmail.com>"]
packages = [{include = "mini_toolbox"}]

[tool.poetry.dependencies]
python = "^3.12"
argsense = "*"
hyperdiv = "^0.1.3"
ipython = "*"
lk-logger = "*"
# lk-utils = "^2.10.7"
lk-utils = { version = "^2.10.8a2", source = "likianta-host" }
streamlit = "^1.36.0"
# streamlit-shadcn-ui = "^0.1.17"
# watchdog = "*"  # <- streamlit

[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
priority = "primary"

[[tool.poetry.source]]
name = "likianta-host"
url = "http://likianta.pro:2006/"
priority = "supplemental"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
