[tool.poetry]
name = "mini-toolbox"
version = "0.1.0"
description = ""
authors = ["likianta <likianta@foxmail.com>"]
packages = [{include = "mini_toolbox"}]

[tool.poetry.dependencies]
python = "^3.11"
argsense = "*"
ipython = "*"
lk-logger = "*"
lk-utils = "*"
pysignal = { version = "^1.0.0", source = "likianta-hosted" }

# projects/car_energy_consumption
streamlit = "^1.29.0"
# streamlit-shadcn-ui = "^0.1.17"
watchdog = "*"  # <- streamlit

[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
priority = "default"

[[tool.poetry.source]]
name = "likianta-hosted"
url = "http://likianta.pro:2006/"
priority = "supplemental"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
