[tool.poetry]
name = "mini-toolbox"
version = "0.1.0"
description = ""
authors = ["likianta <likianta@foxmail.com>"]
packages = [{include = "mini_toolbox"}]

[tool.poetry.dependencies]
python = "^3.12"
# argsense = "*"
argsense = { version = "^0.5.9a0", source = "likianta-host" }
# hyperdiv = "^0.1.3"
ipython = "*"
lk-logger = { version = "^6.0.2", source = "likianta-host" }
lk-utils = { version = "^3.0.2a7", source = "likianta-host" }
pillow = "^10.4.0"
pyperclip = "^1.9.0"
streamlit = "^1.39.0"
streamlit-canary = { version = "^0.1.0a4", source = "likianta-host" }
# streamlit-shadcn-ui = "^0.1.17"

[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
priority = "primary"

[[tool.poetry.source]]
name = "likianta-host"
url = "http://likianta.pro:2131/"
priority = "supplemental"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
