[tool.poetry]
name = "pyapp-window"
version = "0.2.1a0"
description = ""
authors = ["likianta <likianta@foxmail.com>"]
# readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
argsense = "*"
toga = "^0.3.0"

# explicitly specify version for toga dependency on windows.
pythonnet = { version = "^3.0.0", python = ">=3.8,<3.13", platform = "win32" }  # <- toga (windows)

[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
priority = "default"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
